POST http://localhost:3001/users
Content-Type: application/json

{
  "username": "johndoe",
  "password": "securepassword123",
  "email": "johndoe@example.com",
  "profilePicture": "https://example.com/profile.jpg",
  "role": "fan",
  "banned": false
}
