export const ROUTES = {
    HOME: '/',
    LOGIN: '/login',
    REGISTER: '/register',
    PROFILE: '/profile',
    EDIT_PROFILE: '/profile/edit',
    USER_PROFILE: '/profile/:username',
    USER_LIST: '/admin/users',
    CREATE_USER: '/admin/create',
    ADD_REQUEST: '/newrequest',
    REQUEST_LIST: '/requests',
    REQUEST_DETAILS: '/requests/:id',
    ADD_POLL: '/admin/poll',
    REPORT_LIST: '/admin/reports',
    THIEVES: '/thieves',
    CHAT_LIST: '/chat',
    CHAT: '/chat/:username',
    VERIFY_EMAIL: '/verify-email',
    FORGOT_PASSWORD: '/forgot-password',
    RESET_PASSWORD: '/reset-password',
    POLLS: '/polls',
}